#!/usr/bin/bash

set PATH=/usr/bin:/usr/sbin:/bin:/sbin

if [ $USER != "root" ]; then
	echo "This script must be run as root --> 'sudo -s'"
	exit 1
fi

if [ ! -f /etc/debian_version ]; then
	echo "This script only works on Debian 11"
	exit 1
fi

DV=`head -n1 /etc/debian_version | cut -c1-2`
if [ x"$DV" != "x11" ]; then
	echo "This script only works on Debian 11"
	exit 1
fi

# Variables
INSTALL_PKGS="apache2 php7.4-fpm mariadb-server mariadb-client php7.4-mysql git jq avahi-daemon"
APACHE_MODS="headers proxy_fcgi rewrite ssl"

JS="/root/ffdl-jumpstart"

echo "Installing application packages from Debian/RasperryOS repositories..."

apt update -y
apt install -y $INSTALL_PKGS

# Git Repo Pull for Jumpstart
echo "Cloning ffdl-jumpstart for installation services..."
cd /root
git clone https://github.com/jxmx/ffdl-jumpstart.git

# Apache Configuration
a2enmod $APACHE_MODS
cp $JS/apache2/default-ssl.conf $JS/apache2/000-default.conf /etc/apache2/sites-available
a2ensite default-ssl
systemctl enable apache2
systemctl restart apache2

# MariaDB Configuration
mysql -u root <<EOF
create database ffdl;
use ffdl;
grant all on ffdl.* to ffdl@localhost identified by 'ffdl';
EOF

# FFDL Install
FZ=`wget -q -O- https://api.github.com/repos/jxmx/ffdl/releases/latest | jq ".tarball_url" | sed 's/"//g'`
wget -q -O /root/ffdl.tar.gz $FZ
tar xvfz /root/ffdl.tar.gz --strip-components=1 -C /var/www/html
mysql -u root ffdl < /var/www/html/load.sql

# MDNS
systemctl enable avahi-daemon
systemctl restart avahi-daemon

# Cleanup
rm -f /root/ffdl.tar.gz
rm -rf /root/ffdl-jumpstart
